# Function to return background colour based on value of x
success_col_func <- function(x, background = "white", breaks = c(0, 0.05, 0.25, 0.45, Inf)) {
    # Define colour palette
    col_palette <- c("#EF3F27", "#FEC76B", "#F2EF92", "#A3D09C")
    # Check which values in x are numeric
    numeric_x_bool <- !is.na(x)

    # Create a new vector to hold the colours
    new_x <- rep(background, length(x))

    # Only apply colouring to numeric values
    if (sum(numeric_x_bool) > 0) {
        # Cut numeric values into bins and assign colours
        col_cut <- cut(x[numeric_x_bool],
            breaks = breaks,
            include.lowest = TRUE, label = FALSE, right = FALSE
        )
        # Assign colours based on bins
        new_x[numeric_x_bool] <- col_palette[col_cut]
    }

    return(new_x)
}

# Wrap success_col_func with bg1
success_col_func_deploy <- function(x) {
    return(success_col_func(x, seatrackRtools::table_bg$deployed_bg))
}
# Wrap success_col_func with bg2
success_col_func_retrieved <- function(x) {
    return(success_col_func(x, seatrackRtools::table_bg$retrieved_bg))
}

#' Export the flextable to an Excel file with formatting
#'
#' This function exports a flextable object generated by `export_appendix_table_excel` to an Excel file, forcing specific formatting such as column widths, row heights, and text rotation.
#'
#' @param ft A flextable object to be exported
#' @param file_path The file path where the Excel file will be saved
#' @param sheet_name The name of the worksheet in the Excel file (default is "table")
#' @param body_cell_width The width of the body cells (default is 4)
#' @param species_height The height of the species header row (default is 100)
#' @param lme_width The width of the LME column (default is 4)
#' @examples
#' \dontrun{
#' export_appendix_table_excel(ft, "appendix_table.xlsx")
#' }
#' @export
#' @importFrom openxlsx2 wb_workbook wb_set_col_widths wb_set_row_heights int2col
#' @importFrom flexlsx wb_add_flextable
#' @concept annual_report
export_appendix_table_excel <- function(ft, file_path, sheet_name = "table", body_cell_width = 4.5, species_height = 100, lme_width = 4) {
    wb <- openxlsx2::wb_workbook()$add_worksheet(sheet_name)
    wb <- flexlsx::wb_add_flextable(wb, sheet_name, ft)

    lme_range <- paste0("A3:A", nrow(ft$body$content$data) + 3)
    wb$add_cell_style(dims = lme_range, textRotation = 90)
    wb <- openxlsx2::wb_set_col_widths(wb, cols = 1, widths = lme_width)

    species_range <- paste0("C1:", openxlsx2::int2col(ncol(ft$body$content$data)), 1)
    wb$add_cell_style(dims = species_range, textRotation = 90)
    wb <- openxlsx2::wb_set_row_heights(wb, rows = 1, heights = species_height)

    wb <- openxlsx2::wb_set_col_widths(wb, cols = 3:ncol(ft$body$content$data), widths = body_cell_width)

    wb$save(file_path)
}

#' Create a formatted flextable for the appendix table
#'
#' This function generates a flextable summarizing deployment and retrieval data for specified logger types and age classes.
#' It includes background coloring based on success rates and organizes species into groups with distinct colors.
#'
#' @param field_plan_clean Data frame containing the cleaned field plan data
#' @param logger_type Type of logger to filter by (e.g., "GLS", "GPS", "GSM")
#' @param age_target Age class to filter by (e.g., "A" for adult, "C" for chick)
#' @param target_species Vector of species names to include in the table
#' @return A formatted flextable object
#' @examples
#' \dontrun{
#' create_appendix_table(field_plan_clean, "GLS", "A", target_species)
#' }
#' @export
#' @concept annual_report
create_appendix_table_ft <- function(field_plan_clean, logger_type, age_target, target_species) {
    # If Total is not in target_species, add it
    if (!"Total" %in% target_species) {
        target_species <- c(target_species, "Total")
    }

    # Filter field_plan_clean for logger_type and age_target
    field_plan_clean_target <- field_plan_clean[field_plan_clean$logger_type == logger_type & field_plan_clean$age == age_target, c("LME", "Location", "Species", "planned", "retrieved", "deployed", "ret_success", "dep_success")]
    field_plan_clean_target$prev_deployed <- NULL


    # Create wide table with pivot_wider
    wide_table <- tidyr::pivot_wider(field_plan_clean_target,
        names_from = c("Species"),
        values_from = c("planned", "retrieved", "deployed", "ret_success", "dep_success"),
        names_sep = "_._"
    )

    # Get indices of deployed and retrieved columns
    deployed_idx <- grep("deployed", names(wide_table))
    retrieved_idx <- grep("retrieved", names(wide_table))



    # Add total columns
    if (logger_type != "GPS-GSM") {
        wide_table$retrieved_._Total <- rowSums(wide_table[, retrieved_idx], na.rm = TRUE)
        wide_table$ret_success_._Total <- NA
    } else {
        wide_table[, retrieved_idx] <- NULL
        wide_table[, grep("ret_success", names(wide_table))] <- NULL
    }

    # Get indices of deployed and retrieved columns
    deployed_idx <- grep("deployed", names(wide_table))
    retrieved_idx <- grep("retrieved", names(wide_table))

    wide_table$deployed_._Total <- rowSums(wide_table[, deployed_idx], na.rm = TRUE)
    wide_table$dep_success_._Total <- NA

    # Get indices of columns matching target_species
    species_indices <- unlist(lapply(target_species, function(species) {
        grep(tolower(species), tolower(names(wide_table)))
    }))

    # Create species_table with only the columns in species_indices
    species_table <- data.frame(wide_table[, species_indices])

    # split col names by _._ and keep second part
    species_table_species <- unlist(lapply(names(species_table), function(x) {
        parts <- strsplit(x, "_._")[[1]]
        return(parts[2])
    }))

    # fuzzy match col_keys_species to target_species
    species_table_species_matched <- unlist(lapply(species_table_species, function(x) {
        match <- agrep(x, target_species, max.distance = 0.2, value = TRUE, ignore.case = TRUE)
        if (length(match) > 0) {
            return(match[1])
        } else {
            return(x)
        }
    }))

    species_groups <- seatrackRtools::species_groups

    # Order species_table columns by the order of species in species_groups
    species_order <- order(match(tolower(species_table_species_matched), tolower(species_groups$species)))

    # Reorder species_table columns based on species_order
    species_table <- species_table[, species_order]

    # Add LME and Location columns to species_table
    species_table <- data.frame(LME = wide_table$LME, Location = wide_table$Location, species_table)

    # Get new deployed and retrieved indices after reordering
    deployed_idx <- grep("deployed", names(species_table))
    retrieved_idx <- grep("retrieved", names(species_table))

    dr_idx <- sort(c(deployed_idx, retrieved_idx))
    col_keys <- names(species_table)[dr_idx]
    # All column keys including LME and Location
    all_col_keys <- c("LME", "Location", col_keys)

    # Get unique species names in the corect order
    new_species <- unique(species_table_species_matched[species_order])

    # If a value of new_species is greater than 20 characters, replace only the first space with a line break using regex
    new_species_lb <- new_species
    long_species <- nchar(new_species_lb) > 20
    # replace only the first space with a line break
    new_species_lb[long_species] <- sub(" ", "\n", new_species_lb[long_species], fixed = TRUE)

    ## r_d labels
    # Create r_d_labels list with "R" and "D" for each species in new_species
    r_d_labels <- rep(c("R", "D"), length(new_species))
    r_d_labels <- as.list(r_d_labels)

    # Set names of r_d_labels to col_keys
    names(r_d_labels) <- col_keys

    # Add empty labels for LME and Location
    r_d_labels <- c(list(LME = "", Location = ""), r_d_labels)


    # Indices of deployment and retrieval success columns for background colouring
    dep_success_idx <- sapply(unique(species_table_species[species_order]), function(x) {
        which(grepl(x, names(species_table)) & grepl("dep_success", names(species_table)))
    })
    deployment_idx <- sapply(unique(species_table_species[species_order]), function(x) {
        which(grepl(x, names(species_table)) & grepl("deployed", names(species_table)))
    })
    ret_success_idx <- sapply(unique(species_table_species[species_order]), function(x) {
        which(grepl(x, names(species_table)) & grepl("ret_success", names(species_table)))
    })
    retrieval_idx <- sapply(unique(species_table_species[species_order]), function(x) {
        which(grepl(x, names(species_table)) & grepl("retrieved", names(species_table)))
    })

    if (logger_type != "GPS-GSM") {
        # create footer
        footer <- data.frame(col_keys = all_col_keys, values = c("", "Total", colSums(species_table[, sort(c(deployment_idx, retrieval_idx))], na.rm = TRUE)))
    } else {
        footer <- data.frame(col_keys = all_col_keys, values = c("", "Total", colSums(species_table[, sort(c(deployment_idx))], na.rm = TRUE)))
    }




    ### Start flextable creation
    ft <- flextable(species_table, col_keys = all_col_keys, use_labels = FALSE)
    ft <- set_footer_df(ft, mapping = footer)
    ft <- theme_box(ft)
    if (logger_type != "GPS-GSM") {
        ft <- set_header_labels(ft, values = r_d_labels)
    } else {
        ft <- set_header_labels(ft, values = c("", "", rep("Dep", length(new_species))))
    }


    ### Background colours
    # set bg colours
    # Set background colours for deployment and retrieval success columns based on value
    ft <- bg(ft,
        j = names(species_table)[deployment_idx],
        bg = success_col_func_deploy,
        source = names(species_table)[dep_success_idx],
        part = "body"
    )
    if (logger_type != "GPS-GSM") {
        ft <- bg(ft,
            j = names(species_table)[retrieval_idx],
            bg = success_col_func_retrieved,
            source = names(species_table)[ret_success_idx],
            part = "body"
        )
    }
    # Alternating background colours for header row
    ft <- bg(ft,
        j = seq(1, length(all_col_keys), 2),
        part = "header", bg = seatrackRtools::table_bg$retrieved_bg
    )
    ft <- bg(ft,
        j = seq(2, length(all_col_keys), 2),
        part = "header", bg = seatrackRtools::table_bg$deployed_bg
    )

    ### LME formatting
    # Merge the LME cells and set background colour
    ft <- merge_v(ft, j = ~LME)
    # Rotate label
    ft <- rotate(ft, j = 1, rotation = "btlr", part = "body")
    # Set colours
    ft <- bg(ft, j = 1, bg = "#BDD6D5", part = "body")
    ft <- bg(ft, bg = "#BDD6D5", i = 1, j = 1, part = "footer")
    # Merge the top-left cells and set background colour
    ft <- merge_at(ft, i = 1, j = c(1:2), part = "header")
    ft <- bg(ft, bg = "#69A4A4", i = 1, j = 1, part = "header")

    # Footer formatting
    ft <- bg(ft, bg = "#D2D3D5", j = 2:length(all_col_keys), part = "footer")
    ft <- italic(ft, italic = FALSE, part = "footer")

    ### Column widths
    # Get suggested dimensions of the flextable
    ft_dims <- dim_pretty(ft, part = "all")
    # Get the maximum suggested width and height of the cells
    ft_dims_cells <- lapply(ft_dims, function(x) {
        max(x[c(3:length(x))])
    })



    ### Species header row
    # Add a header row above the existing header with species names spanning two columns each
    if (logger_type != "GPS-GSM") {
        ft <- add_header_row(ft, values = c("Location", new_species_lb), colwidths = rep(2, length(new_species) + 1))
    } else {
        ft <- add_header_row(ft, values = c("Location", new_species_lb), colwidths = c(2, rep(1, length(new_species))))
    }

    # Merge the top-left cells
    ft <- merge_at(ft, j = c(1:2), i = c(1:2), part = "header")
    # Set background colours for species groups
    if (logger_type != "GPS-GSM") {
        ft <- bg(ft, i = 1, j = c(3:length(all_col_keys)), bg = rep(species_groups$colour[match(tolower(new_species), tolower(species_groups$species))], each = 2), part = "header")
    } else {
        ft <- bg(ft, i = 1, j = c(3:length(all_col_keys)), bg = rep(species_groups$colour[match(tolower(new_species), tolower(species_groups$species))], each = 1), part = "header")
    }
    # Rotate species names
    ft <- rotate(ft, i = 1, j = c(3:length(all_col_keys)), rotation = "btlr", part = "header")

    ### Alignments
    # Everything center
    ft <- align(ft, align = "center", part = "all")
    # Locations left aligned
    ft <- align(ft, align = "left", part = "body", j = 2)
    # Location header label left aligned and at bottom of cell
    ft <- align(ft, align = "left", part = "header", j = 1)
    ft <- valign(ft, valign = "bottom", part = "header", j = 1)

    # Set numeric cell widths based on the maximum width
    ft <- width(ft, width = ft_dims_cells$widths, j = col_keys)
    # Try to force the location column to be wider
    ft <- width(ft, width = ft_dims$widths[2], j = "Location")

    return(ft)
}



get_logger_info <- function(species, projects, retrieval_years, deployment_years) {
    # seatrackRdb
    # Check if there is a seatrack DB data connection

    seatrackR:::checkCon()

    logger_info <- seatrackR::getLoggerInfo()
    logger_info <- logger_info[logger_info$deployment_species %in% species & logger_info$project %in% projects, ]
    logger_info <- logger_info[!is.na(logger_info$deployment_data) & !is.na(logger_info$retrieval_date)]
    logger_info <- logger_info[logger_info$download_type %in% c("Successfully downloaded", "Reconstructed")]
    logger_info$deployment_year <- format(logger_info$retrieval_date, "%Y")
    logger_info$retrieval_year <- format(logger_info$retrieval_date, "%Y")


    logger_info_by_retrieval_year <- arrange(logger_info, "retrieval_year")

    retrievals_per_year <- summarise(logger_info[logger_info$retrieval_year %in% retrieval_years, ], n_retrievals = n(), by = "retrieval_year")

    deployments_per_year <- summarise(logger_info[logger_info$deployment_year %in% deployment_years, ], n_deployments = n(), by = "deployment_year")
}



# Not used at the moment
# get_logger_tables <- function(field_plan_clean, species) {
#     val_cols <- c("deployed", "planned", "retrieved", "dep_success", "ret_success")
#     all_tables <- lapply(val_cols, function(val_col) {
#         get_logger_table(field_plan_clean, val_col, species)
#     })
#     names(all_tables) <- val_cols
#     return(all_tables)
# }

# # tidyr
# get_logger_table <- function(field_plan_clean, val_col, species) {
#     logger_table <- tidryr::pivot_wider(field_plan_clean,
#         names_from = c(Species),
#         values_from = val_col
#     )
#     logger_table_species <- logger_table[, c(c("LME", "Location", "logger_type", "age"), species)]

#     return(logger_table_species)
# }
